<#
.SYNOPSIS
    Garnet transport A/B on Windows: SocketSet (IOCP / RIO) against stock Garnet SAEA.

.DESCRIPTION
    The Windows counterpart to run-proxy-ab.sh / run-mux-ab.sh, which are Linux-only as written
    (taskset, /proc). Until this existed, every Garnet figure in RESULTS.md was Linux.

    Verify-GarnetDemo.ps1 is the correctness gate and runs FIRST unless -SkipVerify: a leg that serves
    the wrong bytes fast is not a result. That ordering mirrors Run-SmokeMatrix preceding the transport
    rigs.

    FOUR CONFOUNDERS THIS RIG EXISTS TO AVOID. Each one produced clean-looking wrong numbers on
    2026-08-07/08 before it was understood; see TODO.md and IOCP-VS-RIO.md.

    1. ONE BENCHMARK PROCESS CANNOT SATURATE THE SERVER, and adding -c does not help. A single
       resp-benchmark process is bounded around ~270k ops/s however many connections it holds: 200
       connections in one process measured NO BETTER than 50 (262,747 against 276,514), while the same
       200 across four processes reached 444,192. So load is generated by -Processes separate processes
       and SUMMED. Do not "simplify" this back to one process with a big -c.

    2. -c IS NOT A CONNECTION COUNT ON EVERY CLIENT BUILD. resp-benchmark's classic leg used to hand one
       shared ConnectionMultiplexer to every worker, so -c 50 opened ONE connection. The fix reports a
       `conns:` field on its banner; the old build has no such field. This rig therefore GATES on
       `conns:` being present AND equal to what was asked, and REFUSES to run otherwise -- because the
       old build fails silently, producing single-connection numbers under any -c you like. Trust the
       banner, not the flag.

    3. PIPELINE DEPTH IS THE AXIS THAT SEPARATES THE BACKENDS, so -Depths is swept and never fixed. RIO
       carries a ~3us per-completion floor that is only ever amortised, so at -P 1 it runs 13-25x behind
       IOCP and by -P 16 it is comparable. A rig that tested only -P 1 would report RIO as broken; one
       that tested only -P 16 would report parity. Both would be true, and both would mislead.

    4. A SERVER AT 40% OF THE BOX IS NOT BEING MEASURED. Server CPU is reported next to every figure. On
       this hardware the generator competes with the server for the same cores, and several cells sit at
       ~9-10 of 24 cores -- meaning the true ceiling is above the number printed. A cell whose server is
       far from saturated bounds the GENERATOR, not the transport.

    House rules otherwise as usual: six scored passes with the first discarded, leg order reshuffled per
    pass, ranges reported rather than medians alone, and every leg measured in the SAME session as its
    controls.

.PARAMETER BenchmarkExe
    resp-benchmark. Defaults to the sibling StackExchange.Redis source build, because the NuGet-pinned
    3.1.13 is the one-connection build described in confounder 2 and cannot be used for this rig. Re-point
    at the global tool once a fixed version is published.

.EXAMPLE
    .\Run-GarnetAb.ps1
.EXAMPLE
    .\Run-GarnetAb.ps1 -Depths 1,16 -Backends iocp,rio,stock -Passes 7
.EXAMPLE
    .\Run-GarnetAb.ps1 -SkipVerify -Processes 4 -ConnectionsPerProcess 50
#>
[CmdletBinding()]
param(
    [string[]]$Backends = @("iocp", "rio", "stock"),
    # Swept, never fixed - see confounder 3.
    [int[]]$Depths = @(1, 4, 16),
    [string[]]$Tests = @("GET"),
    # Load is generated by N processes summed, not one process with a big -c - see confounder 1.
    [int]$Processes = 4,
    [int]$ConnectionsPerProcess = 50,
    [int]$OperationsPerProcess = 300000,
    # First is discarded as cold, so 7 gives the six scored passes the house rules ask for.
    [int]$Passes = 7,
    [int]$Shards = 12,
    [int]$BasePort = 7600,
    [string]$Configuration = "Release",
    [string]$BenchmarkExe = "C:\Code\StackExchange.Redis\src\RESPite.Benchmark\bin\Release\net10.0\RESPite.Benchmark.exe",
    [switch]$SkipVerify,
    [string]$Filter = "*"
)

$ErrorActionPreference = "Stop"

# `pwsh -File Run-GarnetAb.ps1 -Backends iocp,rio` passes ONE string "iocp,rio", not an array (only the
# -Command form splits on commas). Left alone that becomes a backend literally named "iocp,rio" and
# surfaces as a baffling "server did not listen on 7600". Normalise so both invocation forms agree -- a
# flag that quietly means something else is the failure mode this repo exists to avoid.
$Backends = @($Backends | ForEach-Object { $_ -split ',' } | Where-Object { $_ })
$Tests = @($Tests | ForEach-Object { $_ -split ',' } | Where-Object { $_ })

$repo = Split-Path -Parent $PSScriptRoot
$stamp = Get-Date -Format "yyyyMMdd-HHmmss"
$outDir = Join-Path $repo "bench\results\garnet-ab-$stamp"
New-Item -ItemType Directory -Force $outDir | Out-Null
$csv = Join-Path $repo "bench\results\garnet-ab-$stamp.csv"

$exe = Join-Path $repo "GarnetDemo\bin\$Configuration\net10.0\GarnetDemo.exe"
if (-not (Test-Path $exe)) { throw "GarnetDemo not built: $exe" }
if (-not (Test-Path $BenchmarkExe)) {
    throw @"
resp-benchmark not found at: $BenchmarkExe
Build it:  dotnet build C:\Code\StackExchange.Redis\src\RESPite.Benchmark\RESPite.Benchmark.csproj -c Release -f net10.0
The NuGet-pinned 3.1.13 is NOT a substitute - it is the one-connection build (see confounder 2).
"@
}

Write-Host "Run-GarnetAb -- $stamp" -ForegroundColor Cyan
Write-Host "  server    : $exe"
Write-Host "  generator : $BenchmarkExe"
Write-Host "  load      : $Processes procs x $ConnectionsPerProcess conns = $($Processes * $ConnectionsPerProcess) connections, summed"
Write-Host "  cores     : $([Environment]::ProcessorCount) logical"
Write-Host ""

# ---- correctness gate first: a leg that serves the wrong bytes fast is not a result ----------------
if (-not $SkipVerify) {
    Write-Host "running Verify-GarnetDemo (correctness gate) ..." -ForegroundColor Cyan
    $vOut = & pwsh -NoProfile -File (Join-Path $PSScriptRoot "Verify-GarnetDemo.ps1") 2>&1
    $vOut | Out-File -FilePath (Join-Path $outDir "verify-garnetdemo.txt")
    if (-not ($vOut -match "all cells PASS")) {
        $vOut | Select-Object -Last 20 | ForEach-Object { Write-Host "  $_" }
        throw "Verify-GarnetDemo did not report all cells PASS - fix correctness before measuring."
    }
    Write-Host "  PASS (full output in $outDir\verify-garnetdemo.txt)" -ForegroundColor Green
    Write-Host ""
}

function Start-Server([string]$backend, [int]$port, [string]$log) {
    $args = if ($backend -eq "stock") { @("--stock") } else { @("--backend", $backend) }
    $args += @("--shards", $Shards, "--port", $port)
    $p = Start-Process $exe -ArgumentList $args -PassThru -WindowStyle Hidden `
        -RedirectStandardOutput $log -RedirectStandardError "$log.err"
    for ($i = 0; $i -lt 80; $i++) {
        if (Get-NetTCPConnection -LocalPort $port -State Listen -ErrorAction SilentlyContinue) { return $p }
        if ($p.HasExited) { break }
        Start-Sleep -Milliseconds 250
    }
    try { Stop-Process -Id $p.Id -Force -ErrorAction Stop } catch { }
    throw "server did not listen on $port (backend=$backend); see $log.err"
}

# House rule 1: the SERVER must report what it actually did, not what we asked for.
function Assert-ServerBanner([string]$log, [string]$backend) {
    $banner = (Get-Content $log -ErrorAction SilentlyContinue | Where-Object { $_ -match "\[garnet-demo\]" } | Select-Object -First 1)
    if (-not $banner) { throw "no [garnet-demo] banner in $log - cannot confirm what the server did" }
    $want = if ($backend -eq "stock") { "transport=garnet-saea" } else { "transport=socketset/$backend" }
    if ($banner -notmatch [regex]::Escape($want)) {
        throw "server banner disagrees with the requested leg. wanted '$want', got: $banner"
    }
    return $banner
}

# House rule 1 again, on the CLIENT - and this one is load-bearing, see confounder 2.
function Assert-ClientConns([string]$text, [int]$expected, [string]$where) {
    $m = [regex]::Match($text, 'conns:\s*([\d,]+)')
    if (-not $m.Success) {
        throw @"
resp-benchmark reported no 'conns:' on its banner ($where).
That means the ONE-CONNECTION build: -c is being read as concurrency, not connections, so every figure
would be single-connection whatever -c says. Refusing to measure. Use a build that reports conns:.
"@
    }
    $got = [int]($m.Groups[1].Value -replace ',', '')
    if ($got -ne $expected) { throw "client opened $got connections, expected $expected ($where)" }
    return $got
}

$rows = @()
$cells = @()
foreach ($t in $Tests) { foreach ($d in $Depths) { $cells += @{ Test = $t; Depth = $d } } }

foreach ($cell in $cells) {
    $test = $cell.Test; $depth = $cell.Depth
    Write-Host "===== $test  -P $depth  ($($Processes * $ConnectionsPerProcess) connections) =====" -ForegroundColor Cyan

    # Per-cell results keyed by backend, so the reshuffle below cannot misattribute a pass.
    $acc = @{}; foreach ($b in $Backends) { $acc[$b] = @{ Totals = @(); Cores = @() } }

    for ($pass = 1; $pass -le $Passes; $pass++) {
        # Reshuffled per pass: a fixed order lets a warming or drifting host bias whichever leg runs first.
        foreach ($backend in ($Backends | Sort-Object { Get-Random })) {
            $name = "$backend/$test/P$depth"
            if ($name -notlike $Filter -and $backend -notlike $Filter) { continue }

            $port = $BasePort + ($cells.IndexOf($cell) * 10) + ([array]::IndexOf($Backends, $backend))
            $log = Join-Path $outDir "$backend-$test-P$depth-pass$pass.server.log"
            $srv = Start-Server $backend $port $log
            try {
                $banner = Assert-ServerBanner $log $backend

                $cpu0 = (Get-Process -Id $srv.Id).TotalProcessorTime
                $sw = [Diagnostics.Stopwatch]::StartNew()
                $procs = @(); $files = @()
                for ($k = 0; $k -lt $Processes; $k++) {
                    $f = Join-Path $outDir "$backend-$test-P$depth-pass$pass-p$k.txt"
                    $files += $f
                    $procs += Start-Process $BenchmarkExe -PassThru -WindowStyle Hidden -RedirectStandardOutput $f `
                        -ArgumentList @("-h", "127.0.0.1", "-p", $port, "-c", $ConnectionsPerProcess,
                                        "-P", $depth, "-n", $OperationsPerProcess, "-t", $test, "-q")
                }
                $procs | Wait-Process
                $sw.Stop()
                $cpuSec = ((Get-Process -Id $srv.Id).TotalProcessorTime - $cpu0).TotalSeconds
                $cores = [math]::Round($cpuSec / $sw.Elapsed.TotalSeconds, 2)

                $rates = @()
                foreach ($f in $files) {
                    $txt = Get-Content $f -Raw
                    [void](Assert-ClientConns $txt $ConnectionsPerProcess $name)
                    $m = [regex]::Match($txt, "$([regex]::Escape($test)):\s+([\d,]+)")
                    if (-not $m.Success) { throw "no '${test}:' rate line from a generator ($name); see $f" }
                    $rates += [int]($m.Groups[1].Value -replace ',', '')
                }
                $total = ($rates | Measure-Object -Sum).Sum

                $acc[$backend].Totals += $total
                $acc[$backend].Cores += $cores
                $tag = if ($pass -eq 1) { "cold, discarded" } else { "scored" }
                Write-Host ("  pass {0}  {1,-22} {2,10:#,##0} ops/s   {3,5:0.00} cores   ({4})" -f $pass, $name, $total, $cores, $tag)

                $rows += [pscustomobject]@{
                    Stamp = $stamp; Test = $test; Depth = $depth; Backend = $backend; Pass = $pass
                    Scored = ($pass -gt 1); TotalOpsPerSec = $total; ServerCores = $cores
                    Processes = $Processes; ConnsPerProcess = $ConnectionsPerProcess
                    TotalConns = $Processes * $ConnectionsPerProcess; Shards = $Shards; Banner = $banner
                }
            }
            finally {
                try { Stop-Process -Id $srv.Id -Force -ErrorAction Stop } catch { }
                Start-Sleep -Milliseconds 1200   # let the port release; a reused port exits 255
            }
        }
    }

    Write-Host ""
    Write-Host ("  {0,-10} {1,12} {2,12} {3,12}   {4}" -f "leg", "min", "median", "max", "server cores") -ForegroundColor Cyan
    foreach ($b in $Backends) {
        $scored = @($acc[$b].Totals | Select-Object -Skip 1)
        if ($scored.Count -eq 0) { continue }
        $sorted = @($scored | Sort-Object)
        $median = $sorted[[math]::Floor($sorted.Count / 2)]
        $c = @($acc[$b].Cores | Select-Object -Skip 1)
        Write-Host ("  {0,-10} {1,12:#,##0} {2,12:#,##0} {3,12:#,##0}   {4:0.0}-{5:0.0} of {6}" -f `
            $b, $sorted[0], $median, $sorted[-1], ($c | Measure-Object -Min).Minimum, ($c | Measure-Object -Max).Maximum, [Environment]::ProcessorCount)
    }
    Write-Host ""
}

$rows | Export-Csv -NoTypeInformation -Path $csv
Write-Host "CSV: $csv" -ForegroundColor Green
Write-Host "logs: $outDir" -ForegroundColor Green
Write-Host ""
Write-Host "READ THE RANGES, NOT THE MEDIANS: if two legs' min-max ranges overlap, do not quote a delta." -ForegroundColor Yellow
Write-Host "AND CHECK THE CORES: a leg far from saturating the box bounds the GENERATOR, not the transport." -ForegroundColor Yellow
