<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);RESPITE001</NoWarn>
    <ImplicitUsings>enable</ImplicitUsings>
    <Optimize>true</Optimize>
    <ServerGarbageCollection>true</ServerGarbageCollection>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../vendor/RESPite.Vendored.csproj" />
  </ItemGroup>
</Project>
